"use client";
import { RecipePicker } from "./RecipePicker";
import { productAudience, isSample } from "@/lib/storefront/collections";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { ImageLinks } from "@/components/storefront/ImageLinks";
export type EditorMaterial = { id: string; name: string; unit: string; category: string; defaultCost: number | null };
export type EditorVariant = { id?: string; clientId: string; title: string; price: number | string; compareAtPrice: number | string | null; materials: { materialId: string; quantity: number | string }[] };
export type EditorProduct = { id: string; title: string; description: string; category: string; images: string[]; published: boolean; featured: boolean; badge?: string; variants: EditorVariant[] };
function StepIcon({ index, done }: { index: number; done: boolean }) {
  const paths = ["M12 3 3 8v9l9 5 9-5V8l-9-5ZM3 8l9 5 9-5M12 13v9", "M3 4h18v16H3V4ZM3 16l6-6 5 5 3-3 4 4M16 8h.01", "M9 3h6M10 3v6l-6 10v2h16v-2L14 9V3M7 15h10", "M5 3h10l4 4v14H5V3ZM9 11h6M9 15h6", "M9 12l2 2 4-4"];
  return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={done ? "M6 12l4 4 8-8" : paths[index]}/></svg>;
}
const input = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-[#a58a55]";
const blankVariant = (): EditorVariant => ({ clientId: crypto.randomUUID(), title: "", price: "", compareAtPrice: "", materials: [] });
export function ProductEditor({ materials, initial, sample = false }: { materials: EditorMaterial[]; initial?: EditorProduct; sample?: boolean }) {
  const router = useRouter(); const form = useRef<HTMLFormElement>(null); const requestId = useRef<string | null>(null);
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [title, setTitle] = useState(initial?.title || ""); const [sampleType, setSampleType] = useState(initial ? isSample(initial.category) : sample); const [category, setCategory] = useState(initial ? { men: "Men", women: "Women", unisex: "Unisex" }[productAudience(initial.category)] : "Unisex");
  const [description, setDescription] = useState(initial?.description || ""); const [images, setImages] = useState(initial?.images || []);
  const [published, setPublished] = useState(initial?.published || false); const [featured, setFeatured] = useState(initial?.featured || false);
  const [variants, setVariants] = useState<EditorVariant[]>(initial?.variants.length ? initial.variants : [blankVariant()]);
  const [badge, setBadge] = useState(initial?.badge || "");
  const [offers, setOffers] = useState(initial?.variants.some(v => Number(v.compareAtPrice) > Number(v.price)) || false);
  function toggleOffers(value: boolean) { setOffers(value); if (!value) setVariants(current => current.map(v => ({ ...v, compareAtPrice: "" }))); }
  const steps = ["بيانات العطر", "الصور", "الأحجام والوصفات", "الوصف والنشر", "المعاينة والتأكيد"];
  function costing(v: EditorVariant) {
    let cost = 0; const complete = v.materials.length > 0 && v.materials.every(line => {
      const material = materials.find(item => item.id === line.materialId);
      if (!material || material.defaultCost === null || !(Number(line.quantity) > 0)) return false;
      cost += material.defaultCost * Number(line.quantity); return true;
    });
    return <div className="mt-4 rounded-xl bg-[#f5f3eb] p-4 text-sm"><p>تكلفة الوصفة لقطعة: <b>{complete ? `${cost.toFixed(2)} جنيه` : "أكمل كميات وتكاليف الخامات في المخزون"}</b></p>{complete && Number(v.price) > 0 && <p className="mt-2">الربح المتوقع: <b>{(Number(v.price) - cost).toFixed(2)} جنيه</b> · نسبة الربح: {((Number(v.price) - cost) / Number(v.price) * 100).toFixed(2)}٪</p>}<p className="mt-2 text-xs text-slate-500">قبل المصروفات التشغيلية، حسب تكلفة الخامات الحالية. يظهر للإدارة فقط.</p></div>;
  }
  function update(index: number, changes: Partial<EditorVariant>) { setVariants(current => current.map((variant, i) => i === index ? { ...variant, ...changes } : variant)); }
  function next() {
    const fields = form.current?.querySelectorAll<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>("fieldset:not([hidden]) input, fieldset:not([hidden]) select, fieldset:not([hidden]) textarea");
    if (fields && Array.from(fields).some(field => !field.reportValidity())) return;
    if (step === 1 && images.some(url => !url.startsWith("https://"))) { setError("استخدم روابط صور HTTPS صحيحة"); return; }
    if (step === 2 && variants.some(variant => !variant.materials.length || variant.materials.some(line => !materials.some(material => material.id === line.materialId) || !(Number(line.quantity) > 0)))) { setError("اختر خامات كل حجم وحدد كميات صحيحة قبل المتابعة"); return; }
    setError(""); setStep(Math.min(4, step + 1));
  }
  async function save() {
    if (step !== 4 || busy) return; if (offers && !variants.some(v => Number(v.compareAtPrice) > Number(v.price))) { setError("أدخل سعرًا قبل الخصم أعلى من سعر البيع لحجم واحد على الأقل"); setStep(2); return; } setBusy(true); setError("");
    requestId.current ??= crypto.randomUUID();
    try {
      const response = await fetch("/api/products/manage", { method: initial ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId: requestId.current, productId: initial?.id, title, category: sampleType ? `Samples:${category}` : category, description, images, published, featured, badge,
        variants: variants.map(v => ({ ...v, price: Number(v.price), compareAtPrice: v.compareAtPrice === "" || v.compareAtPrice === null ? null : Number(v.compareAtPrice), materials: v.materials.map(m => ({ ...m, quantity: Number(m.quantity) })) })) }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.error || "تعذر الحفظ");
      router.push(`/dashboard/products/${body.data.productId}`);
    } catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  return <form ref={form} onSubmit={event => event.preventDefault()} className="min-w-0 space-y-6 pb-24"><nav className="grid grid-cols-5 gap-2 rounded-2xl bg-white p-2" aria-label="خطوات المنتج">{steps.map((name, index) => <button key={name} type="button" disabled={busy || index > step} aria-current={step === index ? "step" : undefined} onClick={() => setStep(index)} className={`flex min-w-0 flex-col items-center gap-2 rounded-xl px-1 py-3 text-[10px] font-semibold sm:text-sm ${step === index ? "bg-[#191735] text-white" : "border bg-white text-slate-500"}`}><span className="flex h-8 w-8 items-center justify-center rounded-full border text-base" aria-hidden="true"><StepIcon index={index} done={index < step}/></span><span className="text-center leading-4">{name}</span></button>)}</nav>
    {error && <p role="alert" className="sticky top-3 z-10 rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
    <fieldset hidden={step !== 0} disabled={busy || step !== 0} className="space-y-5 rounded-2xl border bg-white p-6"><legend className="px-2 font-bold">بيانات المنتج</legend><label className="block">اسم العطر<input required maxLength={200} value={title} onChange={e => setTitle(e.target.value)} placeholder="عود" className={input} /></label><p className="text-sm text-slate-500">الاسم يجمع كل الأحجام في كارت واحد للعملاء.</p><label className="block">نوع المنتج<select aria-label="نوع المنتج" value={sampleType ? "samples" : "fragrances"} onChange={e => setSampleType(e.target.value === "samples")} className={input}><option value="fragrances">عطر</option><option value="samples">سامبل / تيستر</option></select></label><label className="block">موجّه إلى<select aria-label="موجّه إلى" value={category} onChange={e => setCategory(e.target.value)} className={input}><option value="Men">رجالي</option><option value="Women">حريمي</option><option value="Unisex">للجنسين (Unisex)</option></select></label><p className="text-sm text-slate-500">{sampleType ? "السامبل يظهر في صفحة Samples فقط." : "للجنسين يظهر في قسم الرجال وقسم السيدات."}</p></fieldset>
    <fieldset hidden={step !== 1} disabled={busy || step !== 1} className="min-w-0 rounded-2xl border bg-white p-4 sm:p-6"><legend className="px-2 font-bold">صور العطر</legend><p className="mb-4 text-sm text-slate-500">الصورة الأولى رئيسية، وباقي الصور تظهر في تفاصيل المنتج.</p><ImageLinks name="images" initial={initial?.images || []} onChange={setImages} /></fieldset>
    <fieldset hidden={step !== 2} disabled={busy || step !== 2} className="space-y-5"><legend className="mb-4 font-bold">الأحجام والأسعار والوصفات</legend><label className="flex gap-3 rounded-xl bg-white p-4"><input type="checkbox" checked={offers} onChange={e => toggleOffers(e.target.checked)} />عليه خصم ويظهر في Offers</label>{!materials.length && <p className="rounded-xl bg-amber-50 p-4">أضف الخامات من <Link href="/dashboard/inventory" className="underline">المخزون</Link> قبل حفظ الوصفة.</p>}{variants.map((variant, index) => <section key={variant.clientId} className="space-y-5 rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold">الحجم {index + 1}</h3>{variants.length > 1 && <button type="button" onClick={() => setVariants(current => current.filter((_, i) => i !== index))} className="text-sm text-red-700">إزالة الحجم</button>}</div><div className="grid gap-4 sm:grid-cols-3"><label>الحجم<div className="mb-2 flex flex-wrap gap-2">{[2, 5, 10, 30, 50, 100].map(size => <button key={size} type="button" onClick={() => update(index, { title: `${size} ml` })} className={`rounded-lg border px-3 py-2 text-xs ${variant.title === `${size} ml` ? "bg-[#191735] text-white" : "bg-slate-50"}`}>{size} ml</button>)}</div><input required value={variant.title} onChange={e => update(index, { title: e.target.value })} placeholder="٣٠ مل" className={input} /></label><label>سعر البيع (جنيه)<input required type="number" step="0.01" min="0.01" max="1000000" value={variant.price} onChange={e => update(index, { price: e.target.value })} className={input} /></label>{offers && <label>السعر قبل الخصم<input type="number" step="0.01" min="0.01" max="1000000" value={variant.compareAtPrice ?? ""} onChange={e => update(index, { compareAtPrice: e.target.value })} className={input} /></label>}</div><p className="text-sm font-semibold">خامات قطعة واحدة من هذا الحجم</p><RecipePicker materials={materials} lines={variant.materials} onChange={lines => update(index, { materials: lines })}/>{index > 0 && <button type="button" onClick={() => update(index, { materials: variants[0].materials.map(m => ({ ...m })) })} className="mr-3 text-sm text-[#514b8c]">نسخ خامات الحجم الأول ثم تعديل الكميات</button>}{costing(variant)}</section>)}<button type="button" disabled={variants.length >= 20} onClick={() => setVariants(current => [...current, blankVariant()])} className="w-full rounded-xl border border-dashed border-[#191735] bg-white p-4 font-semibold">+ إضافة حجم آخر</button></fieldset>
    <fieldset hidden={step !== 3} disabled={busy || step !== 3} className="space-y-5 rounded-2xl border bg-white p-6"><legend className="px-2 font-bold">الوصف والنشر</legend><label className="block">نص البادج (اختياري)<input maxLength={24} value={badge} onChange={e => setBadge(e.target.value)} placeholder="20% OFF" className={input} /><span className="mt-2 block text-xs text-slate-500">يظهر فوق صورة المنتج. اتركه فارغًا لإخفائه؛ أسعار البيع تحدد الخصم الفعلي.</span></label><label className="block">وصف المنتج<textarea rows={5} maxLength={10000} value={description} onChange={e => setDescription(e.target.value)} className={input} /></label><label className="flex gap-3"><input type="checkbox" checked={published} onChange={e => setPublished(e.target.checked)} />ظاهر للعملاء في المتجر</label><label className="flex gap-3"><input type="checkbox" checked={featured} onChange={e => setFeatured(e.target.checked)} />يظهر في Best Sellers</label><div className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">{title} · {category}</h3>{variants.map(v => <p key={v.clientId} className="mt-2">{v.title} · {v.compareAtPrice && <del className="text-slate-400">{v.compareAtPrice} </del>}{v.price} جنيه · {v.materials.length} خامات</p>)}</div><p className="text-xs text-slate-500">تعديل الوصفة ينشئ إصدارًا جديدًا. الطلبات القديمة تحتفظ بأسعارها ووصفاتها، والحجم المحذوف يختفي من البيع الجديد.</p></fieldset>
    <fieldset hidden={step !== 4} disabled={busy || step !== 4} className="space-y-5 rounded-2xl border bg-white p-6"><legend className="px-2 font-bold">معاينة المنتج قبل الحفظ</legend><h2 className="text-2xl font-bold">{title}</h2>{badge && <span className="inline-block rounded-lg bg-[#faeab1] px-3 py-1 text-[#191735]">{badge}</span>}<p>{category} · {offers ? "Offers · " : ""}{featured ? "Best Sellers · " : ""}{published ? "سيظهر للعملاء" : "مسودة غير منشورة"}</p><div className="flex gap-3 overflow-auto">{images.map(url => <Image key={url} src={url} alt={title} width={120} height={150} unoptimized className="rounded-xl object-cover" />)}</div><p className="whitespace-pre-wrap">{description || "لم يُضف وصف"}</p>{variants.map(v => <section key={v.clientId} className="rounded-xl border p-4"><h3 className="font-bold">{v.title} · {v.price} جنيه</h3>{v.compareAtPrice && <p>قبل الخصم: {v.compareAtPrice} جنيه</p>}{v.materials.map(m => <p key={m.materialId} className="mt-2 text-sm">{materials.find(item => item.id === m.materialId)?.name} · {m.quantity} {materials.find(item => item.id === m.materialId)?.unit}</p>)}{costing(v)}</section>)}<p className="text-sm text-slate-500">لم يُحفظ المنتج بعد. راجع البيانات ثم اضغط تأكيد الحفظ.</p></fieldset>
    <footer className="sticky bottom-20 z-20 flex gap-2 rounded-2xl border bg-white/95 p-3 shadow-lg backdrop-blur sm:bottom-4"><Link href="/dashboard/products" className="rounded-xl border px-4 py-3 text-sm">إلغاء</Link>{step > 0 && <button type="button" disabled={busy} onClick={() => setStep(step - 1)} className="rounded-xl border px-5 py-3">السابق</button>}{step < 4 ? <button key="next" type="button" onClick={next} className="flex-1 rounded-xl bg-[#191735] p-3 font-semibold text-white">{step === 3 ? "معاينة المنتج" : "التالي"}</button> : <button key="confirm" type="button" onClick={save} disabled={busy || !materials.length} className="flex-1 rounded-xl bg-[#191735] p-3 font-semibold text-white disabled:opacity-50">{busy ? "جارٍ الحفظ…" : initial ? "تأكيد حفظ التعديلات" : "تأكيد حفظ المنتج"}</button>}</footer>
  </form>;
}
