"use client";
import { useState } from "react";
import type { EditorMaterial } from "./ProductEditor";
import { adjustRecipeQuantity, toggleRecipeMaterial, type RecipeLine } from "@/lib/products/recipe-picker";
export function RecipePicker({ materials, lines, onChange }: { materials: EditorMaterial[]; lines: RecipeLine[]; onChange: (lines: RecipeLine[]) => void }) {
  const [search, setSearch] = useState("");
  const groups = [...new Set(materials.map(material => material.category))];
  function quantity(id: string, value: number | string) { onChange(lines.map(line => line.materialId === id ? { ...line, quantity: value } : line)); }
  return <div className="recipe-picker space-y-4"><div className="rounded-2xl bg-[#f5f3f8] p-4"><h4 className="font-bold">كوّن الوصفة بضغطة</h4><p className="mt-2 text-xs leading-6 text-slate-500">اضغط الخامة لإضافتها أو إزالتها، ثم اختر كميتها. الكمية لقطعة واحدة؛ راجع الزيت لكل حجم.</p><input aria-label="بحث الخامات" value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث عن زيت أو زجاجة أو بوكس…" className="mt-3 w-full rounded-xl border bg-white p-3 text-sm"/></div>
    <details className="rounded-2xl border bg-white p-4" open><summary className="cursor-pointer font-semibold">اختيار الخامات · {lines.filter(line => line.materialId).length} محددة</summary>{groups.map(group => { const found = materials.filter(material => material.category === group && material.name.toLowerCase().includes(search.toLowerCase())); return found.length > 0 && <section key={group} className="mt-5"><h5 className="mb-3 text-xs font-semibold text-slate-500">{group}</h5><div className="flex flex-wrap gap-2">{found.map(material => { const selected = lines.some(line => line.materialId === material.id); return <button key={material.id} type="button" aria-pressed={selected} aria-label={`اختيار ${material.name}`} disabled={!selected && lines.filter(line => line.materialId).length >= 30} onClick={() => onChange(toggleRecipeMaterial(lines, material.id))} className={`rounded-xl border px-4 py-3 text-sm transition ${selected ? "border-[#191735] bg-[#191735] text-white" : "bg-white hover:border-[#a58a55]"}`}><span aria-hidden="true">{selected ? "✓ " : "+ "}</span>{material.name}<small className="mr-2 opacity-70">{material.unit}</small></button>; })}</div></section>; })}{!materials.some(material => material.name.toLowerCase().includes(search.toLowerCase())) && <p className="mt-4 text-sm text-slate-500">لا توجد خامات تطابق البحث</p>}</details>
    {!lines.some(line => line.materialId) && <p className="text-sm text-slate-500">اختر خامة واحدة على الأقل لتكوين الوصفة.</p>}
    {lines.filter(line => line.materialId).map(line => { const material = materials.find(item => item.id === line.materialId); const liquid = ["ml", "مل"].includes(material?.unit.trim().toLowerCase() || ""); return <section key={line.materialId} className="rounded-2xl border bg-slate-50 p-4"><div className="mb-4 flex items-start justify-between gap-3"><div><h5 className="font-semibold">{material?.name || "خامة غير متاحة"}</h5><p className="mt-1 text-xs text-slate-500">{material?.category} · {material?.unit}</p></div><button type="button" aria-label={`إزالة ${material?.name}`} onClick={() => onChange(lines.filter(item => item.materialId !== line.materialId))} className="rounded-lg px-3 py-1 text-sm text-red-700">حذف</button></div><div className="flex items-center justify-between gap-3 rounded-xl border bg-white p-2"><button type="button" aria-label={`تقليل كمية ${material?.name}`} disabled={Number(line.quantity) <= (liquid ? 0.5 : 1)} onClick={() => quantity(line.materialId, adjustRecipeQuantity(line.quantity, liquid ? -0.5 : -1))} className="h-10 w-12 rounded-lg border text-xl disabled:opacity-30">−</button><strong className="text-lg" dir="ltr">{line.quantity || 0} {material?.unit}</strong><button type="button" aria-label={`زيادة كمية ${material?.name}`} onClick={() => quantity(line.materialId, adjustRecipeQuantity(line.quantity, liquid ? 0.5 : 1))} className="h-10 w-12 rounded-lg bg-[#191735] text-xl text-white">+</button></div><div className="mt-3 flex flex-wrap gap-2">{(liquid ? [5, 10, 15, 20, 25, 30] : [1, 2, 3, 5]).map(amount => <button key={amount} type="button" aria-pressed={Number(line.quantity) === amount} onClick={() => quantity(line.materialId, amount)} className={`rounded-lg border px-3 py-2 text-xs ${Number(line.quantity) === amount ? "border-[#a58a55] bg-[#f5ecd8]" : "bg-white"}`}>{amount} {material?.unit}</button>)}</div><details className="mt-3"><summary className="cursor-pointer text-xs text-slate-500">كمية دقيقة (اختياري)</summary><label className="mt-2 block text-xs">الكمية ({material?.unit})<input type="number" required min="0.000001" max="10000000" step="any" value={line.quantity} onChange={event => quantity(line.materialId, event.target.value)} className="mt-2 w-full rounded-xl border bg-white p-3"/></label></details></section>; })}
  </div>;
}
