"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import type { CouponInput } from "@/lib/storefront/coupons";
type Row = CouponInput & { id: string; usedCount: number };
const empty: CouponInput = { code: "", type: "percent", value: 10, minOrder: 0, minItems: 0, maxDiscount: null, maxUses: 0, startsAt: null, expiresAt: null, productId: null, scope: "ALL", freeShipping: false, active: true };
const field = "mt-2 block w-full min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-3";
const scopes = { ALL: "كل المنتجات", FRAGRANCES: "العطور فقط", SAMPLES: "السامبلز فقط", MEN: "رجالي", WOMEN: "حريمي", UNISEX: "للجنسين" };
function localDate(value: string | null) { if (!value) return ""; const d = new Date(value); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export function CouponAdmin() {
  const [rows, setRows] = useState<Row[]>([]); const [products, setProducts] = useState<{ id: string; title: string }[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState<CouponInput>(empty); const [editing, setEditing] = useState<string | null>(null); const dialog = useRef<HTMLDialogElement>(null);
  async function load() { setLoading(true); try { const r = await fetch("/api/admin/coupons"); const b = await r.json(); if (!r.ok) throw new Error(b.error); setRows(b.data.coupons); setProducts(b.data.products); } catch (e) { setError(e instanceof Error ? e.message : "تعذر التحميل"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function open(row?: Row) { setError(""); setEditing(row?.id || null); setForm(row ? { ...row } : { ...empty }); dialog.current?.showModal(); }
  function update<K extends keyof CouponInput>(key: K, value: CouponInput[K]) { setForm(f => ({ ...f, [key]: value })); }
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const r = await fetch("/api/admin/coupons", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, id: editing }) }); const b = await r.json(); if (!r.ok) throw new Error(b.error); dialog.current?.close(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "تعذر الحفظ"); } finally { setBusy(false); } }
  async function remove(row: Row) { if (!window.confirm(`حذف الكوبون ${row.code}؟ الطلبات السابقة تحتفظ بخصمها.`)) return; setBusy(true); setError(""); try { const r = await fetch(`/api/admin/coupons?id=${encodeURIComponent(row.id)}`, { method: "DELETE" }); const b = await r.json(); if (!r.ok) throw new Error(b.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : "تعذر الحذف"); } finally { setBusy(false); } }
  const amount = (key: "value" | "minOrder" | "minItems" | "maxUses" | "maxDiscount", label: string, optional = false) => <label>{label}<input className={field} type="number" min={0} max={key === "value" && form.type === "percent" ? 100 : 1000000} step={key === "maxUses" || key === "minItems" ? 1 : "0.01"} value={form[key] ?? ""} required={!optional} onChange={e => update(key, optional && e.target.value === "" ? null : Number(e.target.value))} /></label>;
  return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">الكوبونات</h1><p className="mt-2 text-sm text-slate-500">خصومات وشحن مجاني بشروط تحددها أنت.</p></div><button onClick={() => open()} className="rounded-xl bg-[#191735] px-5 py-3 text-white">+ كوبون جديد</button></header>
    {error && !dialog.current?.open && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}
    <div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4">كل الكوبونات <b className="block text-2xl">{rows.length}</b></div><div className="rounded-2xl bg-white p-4">مرات الاستخدام <b className="block text-2xl">{rows.reduce((n, r) => n + r.usedCount, 0)}</b></div></div>
    {loading ? <p role="status">جارٍ تحميل الكوبونات…</p> : !rows.length ? <p className="rounded-2xl bg-white p-8 text-center">أضف أول كوبون لعملائك.</p> : <div className="grid gap-4 sm:grid-cols-2">{rows.map(row => <article key={row.id} className="min-w-0 space-y-3 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><code className="break-all text-xl font-bold" dir="ltr">{row.code}</code><span className="text-sm">{!row.active ? "متوقف" : row.expiresAt && new Date(row.expiresAt) <= new Date() ? "منتهي" : row.maxUses > 0 && row.usedCount >= row.maxUses ? "نفد" : row.startsAt && new Date(row.startsAt) > new Date() ? "مجدول" : "نشط"}</span></div><p>{row.type === "percent" ? `${row.value}٪` : `${row.value} جنيه`}{row.freeShipping ? " · شحن مجاني" : ""}</p><p className="text-sm text-slate-500">{scopes[row.scope]} · حد أدنى {row.minOrder} جنيه · {row.minItems} قطع</p>{row.productId && <p className="text-sm">منتج: {products.find(p => p.id === row.productId)?.title || "منتج سابق"}</p>}<p className="text-sm">الاستخدام: {row.usedCount} / {row.maxUses || "غير محدود"}</p>{row.expiresAt && <p className="text-sm">ينتهي: {new Date(row.expiresAt).toLocaleString("ar-EG")}</p>}<div className="flex gap-3"><button disabled={busy} onClick={() => open(row)} className="flex-1 rounded-xl border p-3">تعديل</button><button disabled={busy} onClick={() => remove(row)} className="rounded-xl border p-3 text-red-700">حذف</button></div></article>)}</div>}
    <dialog ref={dialog} className="m-auto max-h-[90dvh] w-[calc(100%_-_2rem)] max-w-xl overflow-y-auto rounded-2xl bg-white p-0 text-[#191735] backdrop:bg-black/50" onCancel={e => { if (busy) e.preventDefault(); }}><form onSubmit={save}><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><h2 className="text-xl font-bold">{editing ? "تعديل الكوبون" : "كوبون جديد"}</h2><button type="button" disabled={busy} onClick={() => dialog.current?.close()} aria-label="إغلاق">✕</button></header><fieldset disabled={busy} className="grid min-w-0 gap-4 p-5 sm:grid-cols-2"><label className="sm:col-span-2">كود الخصم<input className={field} dir="ltr" required minLength={2} maxLength={40} pattern="[A-Za-z0-9_-]+" value={form.code} onChange={e => update("code", e.target.value.toUpperCase())} placeholder="AURAIC10" /></label><label>نوع الخصم<select className={field} value={form.type} onChange={e => update("type", e.target.value as CouponInput["type"])}><option value="percent">نسبة مئوية</option><option value="fixed">مبلغ ثابت</option></select></label>{amount("value", "قيمة الخصم")}{amount("minOrder", "الحد الأدنى للطلب (جنيه)")}{amount("minItems", "أقل عدد قطع مؤهلة")}{amount("maxDiscount", "أقصى خصم (اختياري)", true)}{amount("maxUses", "عدد الاستخدامات · 0 = غير محدود")}<label>القسم<select className={field} value={form.scope} onChange={e => update("scope", e.target.value as CouponInput["scope"])}>{Object.entries(scopes).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></label><label>منتج محدد (اختياري)<select className={field} value={form.productId || ""} onChange={e => update("productId", e.target.value || null)}><option value="">كل منتجات القسم</option>{products.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{(["startsAt", "expiresAt"] as const).map((key, i) => <label key={key}>{i ? "تاريخ الانتهاء" : "تاريخ البداية"}<input className={field} type="datetime-local" value={localDate(form[key])} onChange={e => update(key, e.target.value ? new Date(e.target.value).toISOString() : null)} /></label>)}<label className="flex gap-2"><input type="checkbox" checked={form.freeShipping} onChange={e => update("freeShipping", e.target.checked)} />شحن مجاني</label><label className="flex gap-2"><input type="checkbox" checked={form.active} onChange={e => update("active", e.target.checked)} />الكوبون نشط</label><p className="text-xs text-slate-500 sm:col-span-2">الخصم يُحسب على سعر البيع الحالي للمنتجات المؤهلة، ويمكن استخدام كوبون واحد لكل طلب. حد الشحن المجاني يُحسب قبل الخصم.</p>{error && <p role="alert" className="text-red-700 sm:col-span-2">{error}</p>}</fieldset><footer className="sticky bottom-0 border-t bg-white p-4"><button disabled={busy} className="w-full rounded-xl bg-[#191735] p-3 font-bold text-white">{busy ? "جارٍ الحفظ…" : "حفظ الكوبون"}</button></footer></form></dialog>
  </main>;
}
