"use client";
import { ShopIcon } from "./ShopIcon";
import { productAudience, matchesAudience, hasOffer } from "@/lib/storefront/collections";
import Link from "next/link";
import Image from "next/image";
import { useCart } from "./CartProvider";
import { useEffect, useState } from "react";
import type { ShopProduct } from "@/services/storefront/catalog";
import { formatMoney } from "@/lib/storefront/pricing";

const displaySize = (title: string) => /^\d+(?:\.\d+)?$/.test(title.trim()) ? `${title.trim()} ml` : title;

export function ProductCard({ product, showNotes = false, enabled = false }: { product: ShopProduct; showNotes?: boolean; enabled?: boolean }) {
  const cart = useCart(); const [variantId, setVariantId] = useState((product.variants.find(item => /^50\s*(ml|مل)?$/i.test(item.title.trim())) || product.variants[0]).id); const [added, setAdded] = useState(false);
  const variant = product.variants.find(item => item.id === variantId)!;
  const disabled = !enabled || !cart.ready || (cart.lines.length >= 20 && !cart.lines.some(item => item.variantId === variant.id));
  return <article className="shop-product-wrap shop-fragrance-card">
    <div className="shop-card-photo"><Link href={`/products/${product.id}`} className="shop-product-card shop-card-photo-link"><div className="shop-product-image"><Image src={product.images[0] || "/auraic-bottle.svg"} alt={product.name} fill unoptimized={!!product.images.length} sizes="(max-width: 760px) 76vw, 42vw"/></div></Link><div className="shop-card-photo-controls"><button type="button" className="shop-favorite" disabled={!cart.ready} onClick={() => cart.toggleFavorite(product.id)} aria-pressed={cart.favorites.includes(product.id)} aria-label={cart.favorites.includes(product.id) ? "Remove from wishlist" : "Add to wishlist"}><ShopIcon name="heart" fill={cart.favorites.includes(product.id) ? "currentColor" : "none"}/></button><div className="shop-card-badges">{product.badge && <span className="shop-card-custom-badge" title={product.badge}>{product.badge}</span>}<span className="shop-card-size">{displaySize(variant.title)}</span></div></div></div>
    <div className="shop-card-heading"><Link href={`/products/${product.id}`}><h3>{product.name}</h3></Link><div className="shop-fragrance-tags">{product.scentFamily && <span className="shop-scent-tag">{product.scentFamily}</span>}<span style={{ textTransform: "none" }}>{productAudience(product.category) === "men" ? "Men" : productAudience(product.category) === "women" ? "FEMININE" : "UNISEX"}</span></div></div>
    <p className={`shop-card-description ${showNotes ? "expanded shop-product-notes" : ""}`}>{product.description}</p>
    {product.inspiredBy && <p className="shop-inspired"><span>Inspired by</span><strong>{product.inspiredBy}</strong></p>}
    <div className="shop-card-sizes" aria-label={`Choose size for ${product.name}`}>{product.variants.map(item => <button type="button" key={item.id} aria-pressed={item.id === variantId} onClick={() => { setVariantId(item.id); setAdded(false); }}>{displaySize(item.title)}</button>)}</div>
    <p className="shop-card-price">Price <strong>{formatMoney(variant.price)}</strong>{variant.compareAtPrice && <del>{formatMoney(variant.compareAtPrice)}</del>}</p>
    <button type="button" className="shop-button shop-card-add" disabled={disabled} onClick={() => { cart.add({ variantId: variant.id, productId: product.id, name: product.name, size: variant.title, image: product.images[0] || "/auraic-bottle.svg", quantity: 1 }); setAdded(true); }}>{!enabled ? "Orders paused" : added ? "✓ Added to bag" : "Add to bag"}</button><span role="status" className="sr-only">{added ? `${product.name}, ${variant.title} added to bag` : ""}</span>
  </article>;
}
export function Catalog({ products, initialSearch = "", initialAudience = "", initialCollection = "", initialSize = "", enabled }: { products: ShopProduct[]; enabled: boolean; initialSearch?: string; initialAudience?: string; initialCollection?: string; initialSize?: string }) {
  const [audience, setAudience] = useState(initialAudience); const [search, setSearch] = useState(initialSearch); const [sort, setSort] = useState("featured");
  const [size, setSize] = useState(initialSize); const [collection, setCollection] = useState(initialCollection); const [filtersOpen, setFiltersOpen] = useState(true); const [showNotes, setShowNotes] = useState(false);
  useEffect(() => {
    const next = new URL(window.location.href);
    for (const [name, value] of [["audience", audience], ["collection", collection], ["size", size], ["q", search]]) {
      if (value) next.searchParams.set(name, value); else next.searchParams.delete(name);
    }
    if (next.href !== window.location.href) window.history.replaceState(null, "", next.pathname + next.search + next.hash);
  }, [audience, collection, size, search]);
  const sizes = [...new Set(products.flatMap(p => p.variants.map(v => v.title)))];
  const filtered = products.filter(p => (!audience || matchesAudience(p.category, audience)) && (!size || p.variants.some(v => v.title === size)) && (collection !== "offers" || hasOffer(p)) && (collection !== "bestsellers" || p.featured) && p.name.toLowerCase().includes(search.toLowerCase())).sort((a,b) => sort === "low" ? a.variants[0].price-b.variants[0].price : sort === "high" ? b.variants[0].price-a.variants[0].price : Number(b.featured)-Number(a.featured));
  const heading = audience === "men" ? "FRAGRANCES\nFOR MEN" : audience === "women" ? "FRAGRANCES\nFOR WOMEN" : audience === "unisex" ? "UNISEX\nFRAGRANCES" : collection === "offers" ? "FRAGRANCE\nOFFERS" : collection === "bestsellers" ? "BEST\nSELLERS" : "ALL\nFRAGRANCES";
  const chips = [audience && { label: audience === "men" ? "FRAGRANCES FOR MEN" : audience === "women" ? "FRAGRANCES FOR WOMEN" : "UNISEX", clear: () => setAudience("") }, size && { label: size, clear: () => setSize("") }, collection && { label: collection === "offers" ? "OFFERS" : "BEST SELLERS", clear: () => setCollection("") }, search && { label: search, clear: () => setSearch("") }].filter(Boolean) as {label:string;clear:()=>void}[];
  function clear() { setAudience(""); setCollection(""); setSize(""); setSearch(""); }
  return <><header className="shop-collection-heading"><p>AURAIC FRAGRANCES</p><h1>{heading}</h1><small>{filtered.length} FRAGRANCES</small><p className="shop-collection-description">{audience === "men" ? "Explore Auraic fragrances for men, including unisex scents." : audience === "women" ? "Explore Auraic fragrances for women, including unisex scents." : "Discover your next Auraic fragrance. Choose the scent and size that feel like you."}</p></header>
    <section className="shop-collection-tools" aria-label="Fragrance filters"><div className="shop-filter-toolbar"><button type="button" className="shop-filter-button" aria-expanded={filtersOpen} aria-controls="collection-filters" onClick={() => setFiltersOpen(!filtersOpen)}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2" fill="currentColor"/><circle cx="15" cy="12" r="2" fill="currentColor"/><circle cx="9" cy="18" r="2" fill="currentColor"/></svg> FILTER <span>{chips.length}</span></button><label className="shop-sort-control"><span className="shop-sort-label">Sort by</span><select aria-label="Sort fragrances" value={sort} onChange={e => setSort(e.target.value)}><option value="featured">BEST SELLERS</option><option value="low">PRICE: LOW TO HIGH</option><option value="high">PRICE: HIGH TO LOW</option></select></label></div>
    <div id="collection-filters" hidden={!filtersOpen} className="shop-collection-filters"><label>GENDER<select aria-label="Gender" value={audience} onChange={e => setAudience(e.target.value)}><option value="">ALL</option><option value="men">FOR MEN</option><option value="women">FOR WOMEN</option><option value="unisex">UNISEX</option></select></label><label>SIZE<select aria-label="Size" value={size} onChange={e => setSize(e.target.value)}><option value="">ALL SIZES</option>{sizes.map(s => <option key={s}>{s}</option>)}</select></label><label>COLLECTION<select aria-label="Collection" value={collection} onChange={e => setCollection(e.target.value)}><option value="">ALL FRAGRANCES</option><option value="offers">OFFERS</option><option value="bestsellers">BEST SELLERS</option></select></label><label className="shop-collection-search">SEARCH<input aria-label="Search fragrances" placeholder="Find your fragrance" value={search} onChange={e => setSearch(e.target.value)}/></label></div></section>
    <div className="shop-applied-filters"><span>{chips.length} APPLIED</span>{chips.map(c => <button type="button" key={c.label} onClick={c.clear}>{c.label} <b>×</b></button>)}{chips.length > 0 && <button type="button" onClick={clear}>CLEAR ALL</button>}</div><div className="shop-collection-results"><p>{filtered.length} SCENTS<br/><span>{chips.length} ACTIVE REFINEMENTS</span></p><button type="button" role="switch" aria-checked={showNotes} onClick={() => setShowNotes(!showNotes)} className="shop-notes-toggle"><span className="shop-toggle-track"><span/></span> SHOW NOTES</button></div><div className="shop-product-grid">{filtered.map(p => <ProductCard key={p.id} product={p} enabled={enabled} showNotes={showNotes}/>)}</div>{!filtered.length && <div className="shop-empty"><h3>No fragrances found</h3><p>Try clearing a filter to explore more scents.</p><button className="shop-button" type="button" onClick={clear}>Clear filters</button></div>}</>;
}
