"use client";
import { productAudience, matchesAudience, hasOffer } from "@/lib/storefront/collections";
import Link from "next/link";
import Image from "next/image";
import { useCart } from "./CartProvider";
import { useState } from "react";
import type { ShopProduct } from "@/services/storefront/catalog";
import { formatMoney } from "@/lib/storefront/pricing";

export function ProductCard({ product, showNotes = false }: { product: ShopProduct; showNotes?: boolean }) {
  const cart = useCart();
  return <article className="shop-product-wrap"><button type="button" className="shop-favorite" disabled={!cart.ready} onClick={() => cart.toggleFavorite(product.id)} aria-pressed={cart.favorites.includes(product.id)} aria-label={cart.favorites.includes(product.id) ? "Remove from wishlist" : "Add to wishlist"}>{cart.favorites.includes(product.id) ? "♥" : "♡"}</button><Link href={`/products/${product.id}`} className="shop-product-card"><div className="shop-product-image"><Image src={product.images[0] || "/auraic-bottle.svg"} alt={product.name} fill unoptimized={!!product.images.length} sizes="(max-width: 640px) 50vw, 25vw" />{(product.featured || hasOffer(product)) && <span className="shop-product-badge">{product.featured ? "Best Seller" : "Offer"}</span>}<span className="shop-product-arrow">↗</span></div><p>{productAudience(product.category) === "men" ? "For Men" : productAudience(product.category) === "women" ? "For Women" : "Unisex"}</p><h3>{product.name}</h3><div><strong>{product.variants.length > 1 && "From "}{formatMoney(product.variants[0].price)}</strong>{product.variants[0].compareAtPrice && <del>{formatMoney(product.variants[0].compareAtPrice)}</del>}<span>{product.variants.length > 1 ? `${product.variants.length} sizes` : product.variants[0].title}</span></div>{showNotes && <p className="shop-product-notes">{product.description || "Discover the full fragrance on the product page."}</p>}</Link></article>;
}
export function Catalog({ products, initialSearch = "" }: { products: ShopProduct[]; initialSearch?: string }) {
  const [category, setCategory] = useState(""); const [search, setSearch] = useState(initialSearch); const [sort, setSort] = useState("default");
  const filtered = products.filter(product => (!category || matchesAudience(product.category, category)) && product.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "low" ? a.variants[0].price - b.variants[0].price : sort === "high" ? b.variants[0].price - a.variants[0].price : 0);
  return <><div id="shop-search" className="shop-catalog-controls"><label className="shop-search"><span>⌕</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Find your fragrance" aria-label="Search fragrances" /></label><select value={sort} onChange={event => setSort(event.target.value)} aria-label="Sort fragrances"><option value="default">Auraic picks</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><div className="shop-category-tabs"><button className={!category ? "active" : ""} onClick={() => setCategory("")}>All fragrances</button>{[["men", "For Men"], ["women", "For Women"], ["unisex", "Unisex"]].map(([value, label]) => <button key={value} className={category === value ? "active" : ""} onClick={() => setCategory(value)}>{label}</button>)}</div><p className="shop-result-count">{filtered.length} fragrances</p><div className="shop-product-grid">{filtered.map(product => <ProductCard key={product.id} product={product} />)}</div>{!filtered.length && <div className="shop-empty"><h3>No fragrances found</h3><p>Try a different collection or search term.</p></div>}</>;
}
