"use client";
import { useRef, useState } from "react";
import Image from "next/image";
export function ImageLinks({ name, initial, onChange, maxImages = 8 }: { name: string; initial: string[]; onChange?: (images: string[]) => void; maxImages?: number }) {
  const [slots, setSlots] = useState<string[]>(Array.from({ length: Math.min(maxImages, Math.max(Math.min(4, maxImages), initial.length)) }, (_, i) => initial[i] || ""));
  const [uploading, setUploading] = useState<number | null>(null); const [error, setError] = useState(""); const latest = useRef(slots);
  function change(next: string[]) { latest.current = next; setSlots(next); onChange?.(next.map(url => url.trim()).filter(Boolean)); }
  return <div className="space-y-4"><input type="hidden" name={name} value={slots.map(url => url.trim()).filter(Boolean).join("\n")}/><div className="rounded-2xl bg-slate-50 p-5"><h3 className="font-semibold">{maxImages === 1 ? "صورة القسم" : "صور المنتج"}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{maxImages === 1 ? "ارفع تصميمك كصورة واحدة أو أضف رابطها. تظهر كاملة في أعلى صفحة السامبلز." : "الصورة الأولى هي الرئيسية. ارفع الصور من جهازك أو أضف رابطًا، ورتّبها قبل الحفظ."}</p></div>
    {slots.map((url, index) => <section key={index} className="rounded-2xl border bg-white p-4"><div className="mb-3 flex items-center justify-between"><label htmlFor={`${name}-${index}`} className="text-sm text-slate-500">{index === 0 ? "الصورة الرئيسية" : `صورة ${index + 1}`}</label>{url && <button type="button" disabled={uploading !== null} onClick={() => change(slots.map((value, i) => i === index ? "" : value))} className="text-xs text-red-700">حذف الصورة</button>}</div><div className="flex items-center gap-3">{url.startsWith("https://") && <Image src={url} unoptimized width={56} height={66} alt={`الصورة ${index + 1}`} className="h-16 w-14 rounded-lg border object-cover"/>}<input id={`${name}-${index}`} type="url" value={url} disabled={uploading !== null} onChange={event => change(slots.map((value, i) => i === index ? event.target.value : value))} placeholder="رابط الصورة أو ارفع من جهازك" className="min-w-0 flex-1 rounded-xl border px-3 py-3 text-sm" dir="ltr"/><label className="cursor-pointer rounded-xl border border-[#a58a55] px-3 py-3 text-sm text-[#846a37]"><span>{uploading === index ? "…" : "↑ رفع"}</span><input type="file" className="sr-only" aria-label={`رفع الصورة ${index + 1}`} accept="image/jpeg,image/png" disabled={uploading !== null} onChange={async event => {
      const file = event.target.files?.[0]; if (!file) return; event.target.value = ""; setUploading(index); setError("");
      try { const data = new FormData(); data.set("file", file); const response = await fetch("/api/admin/storefront/images", { method: "POST", body: data }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "تعذر رفع الصورة"); change(latest.current.map((value, i) => i === index ? body.data.url : value)); }
      catch (failure) { setError(failure instanceof Error ? failure.message : "تعذر الرفع"); } finally { setUploading(null); }
    }}/></label></div>{url && index > 0 && <button type="button" disabled={uploading !== null} className="mt-3 text-xs text-[#514b8c]" onClick={() => { const next = [...slots]; [next[0], next[index]] = [next[index], next[0]]; change(next); }}>اجعلها الصورة الرئيسية</button>}</section>)}
    {slots.length < maxImages && <button type="button" disabled={uploading !== null} onClick={() => change([...slots, ""])} className="w-full rounded-xl border border-dashed p-3 text-sm">+ صورة أخرى</button>}<p className="text-xs text-slate-500">{maxImages === 1 ? "صورة واحدة." : `حتى ${maxImages} صور.`} JPG أو PNG حتى 3 ميجابايت، أو رابط HTTPS.</p>{uploading !== null && <input type="text" required value="" readOnly className="sr-only" aria-label="انتظر اكتمال رفع الصورة"/>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}
  </div>;
}
