"use client";
import Image from "next/image";
import Link from "next/link";
import { useShopNavigation } from "./ShopNavigation";
import { useState } from "react";
import type { ShopProduct } from "@/services/storefront/catalog";
import { formatMoney } from "@/lib/storefront/pricing";
import { useCart } from "./CartProvider";
export function ProductDetail({ product, enabled }: { product: ShopProduct; enabled: boolean }) {
  const [variantId, setVariantId] = useState(product.variants[0].id); const [quantity, setQuantity] = useState(1); const [photo, setPhoto] = useState(0); const [added, setAdded] = useState(false); const cart = useCart();
  const navigate = useShopNavigation();
  const variant = product.variants.find(item => item.id === variantId)!;
  const images = product.images.length ? product.images : ["/auraic-bottle.svg"];
  return <div className="shop-detail"><div><div className="shop-detail-image"><Image src={images[photo]} alt={product.name} fill unoptimized sizes="(max-width: 760px) 90vw, 50vw" priority /></div>{images.length > 1 && <div className="shop-thumbnails">{images.map((image, index) => <button key={image + index} onClick={() => setPhoto(index)} aria-label={`Image ${index + 1}`} aria-pressed={photo === index}><Image src={image} width={80} height={90} alt="" unoptimized /></button>)}</div>}</div>
    <div className="shop-detail-copy"><p className="shop-eyebrow">{product.category}</p><nav className="shop-breadcrumb"><Link href="/products">Fragrances</Link> / {product.name}</nav><h1>{product.name}</h1><button type="button" className="shop-favorite-detail" disabled={!cart.ready} onClick={() => cart.toggleFavorite(product.id)} aria-pressed={cart.favorites.includes(product.id)}>{cart.favorites.includes(product.id) ? "♥ Saved to wishlist" : "♡ Add to wishlist"}</button><p className="shop-detail-price">{variant.compareAtPrice && <del className="mr-3 text-lg text-slate-400">{formatMoney(variant.compareAtPrice)}</del>}{formatMoney(variant.price)}{variant.compareAtPrice && <span className="mr-3 text-sm text-emerald-700">Save {Math.round((1 - variant.price / variant.compareAtPrice) * 100)}%</span>}</p><p className="shop-description">{product.description || "Choose your size and discover the Auraic experience."}</p><h3>Choose your size</h3><div className="shop-variant-buttons">{product.variants.map(item => <button aria-pressed={item.id === variantId} key={item.id} onClick={() => { setVariantId(item.id); setAdded(false); }}>{item.title}<small>{formatMoney(item.price)}</small></button>)}</div><div className="shop-add-row"><div className="shop-quantity"><button aria-label="Decrease quantity" disabled={quantity === 1} onClick={() => setQuantity(quantity - 1)}>−</button><span>{quantity}</span><button aria-label="Increase quantity" disabled={quantity === 20} onClick={() => setQuantity(quantity + 1)}>+</button></div><button disabled={!enabled || !cart.ready || cart.lines.length >= 20 && !cart.lines.some(item => item.variantId === variant.id)} className="shop-button" onClick={() => { cart.add({ variantId: variant.id, productId: product.id, name: product.name, size: variant.title, image: images[0], quantity }); setAdded(true); }}>{!enabled ? "Orders are currently paused" : added ? "✓ Added to your bag" : "Add to bag"}</button></div><button type="button" className="shop-button shop-buy-now" disabled={!enabled || !cart.ready || cart.lines.length >= 20 && !cart.lines.some(item => item.variantId === variant.id)} onClick={() => { cart.add({ variantId: variant.id, productId: product.id, name: product.name, size: variant.title, image: images[0], quantity }); navigate("/checkout"); }}>Buy now →</button>{added && <Link className="shop-inline-link" href="/cart">View your bag →</Link>}<details className="shop-policy"><summary>Shipping & payment</summary><p>Pay on delivery. Your shipping cost is shown before you confirm. <Link href="/shipping">Delivery information</Link></p></details><details className="shop-policy"><summary>Returns & exchanges</summary><p>Read our <Link href="/returns">returns and exchanges policy</Link> before buying.</p></details><p className="shop-detail-note">Pay on delivery · Read our <Link href="/shipping">shipping policy</Link></p></div></div>;
}
