"use client";
import Image from "next/image";
import { useRef, useState } from "react";
import type { ShopSettings } from "@/lib/storefront/config";
function ScreenshotReviews({ images, title }: { images: string[]; title: string }) {
  const rail = useRef<HTMLDivElement>(null); const [active, setActive] = useState(0);
  return <section className="shop-review-section shop-customer-reviews" aria-label={title}><span className="shop-eyebrow">FROM OUR CUSTOMERS</span><h2>{title}</h2><div ref={rail} className="shop-review-rail shop-screenshot-rail" onScroll={() => { const node = rail.current; if (!node) return; const children = Array.from(node.children) as HTMLElement[]; setActive(children.reduce((best, item, index) => Math.abs(item.offsetLeft - node.offsetLeft - node.scrollLeft) < Math.abs(children[best].offsetLeft - node.offsetLeft - node.scrollLeft) ? index : best, 0)); }}>{images.map((src, index) => <div className="shop-review-screenshot" key={src + index}><Image src={src} alt={`Customer review ${index + 1}`} width={900} height={1100} unoptimized sizes="(max-width:760px) 90vw, 700px"/></div>)}</div>{images.length > 1 && <div className="shop-review-dots">{images.map((_, index) => <button type="button" key={index} aria-label={`Show customer review ${index + 1}`} aria-pressed={active === index} onClick={() => { const node = rail.current; const child = node?.children[index] as HTMLElement | undefined; if (node && child) node.scrollTo({ left: child.offsetLeft - node.offsetLeft, behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" }); }}/>)}</div>}</section>;
}
export function ReviewSections({ settings }: { settings: ShopSettings }) {
  return <>{settings.bloggerReviewsEnabled && settings.bloggerReviewVideos.length > 0 && <section className="shop-review-section shop-blogger-reviews" aria-label={settings.bloggerReviewsTitle}><span className="shop-eyebrow">THE AURAIC EXPERIENCE</span><h2>{settings.bloggerReviewsTitle}</h2><p>Real impressions. Discover the fragrances they love.</p><div className="shop-review-rail">{settings.bloggerReviewVideos.map((src, index) => <div className="shop-review-video" key={src + index}><video src={src} controls playsInline preload="metadata" aria-label={`Blogger review ${index + 1}`} onPlay={event => { const current = event.currentTarget; current.closest('.shop-review-rail')?.querySelectorAll('video').forEach(video => { if (video !== current) video.pause(); }); }}/></div>)}</div></section>}{settings.customerReviewsEnabled && settings.customerReviewImages.length > 0 && <ScreenshotReviews images={settings.customerReviewImages} title={settings.customerReviewsTitle}/>}</>;
}
