"use client";
import { AdminProductPreview } from "@/components/products/AdminProductPreview";
import { productAudience, isSample } from "@/lib/storefront/collections";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { VideoUpload } from "./VideoUpload";
import { ImageLinks } from "./ImageLinks";
import { governorates } from "@/lib/storefront/config";
import type { ShopSettings } from "@/lib/storefront/config";

type PresentationProduct = { variants: { id: string; title: string; price: number; compareAtPrice: number | null }[]; storefrontBadge: string; storefrontInspiredBy: string; storefrontScentFamily: string; id: string; title: string; storefrontPublished: boolean; storefrontFeatured: boolean; storefrontDescription: string; storefrontCategory: string; storefrontImages: string[]; ready: boolean };
const field = "mt-2 block w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#ab8c51]";
const card = "space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7";
const urls = (text: string) => text.split(/\n/).map(value => value.trim()).filter(Boolean);
async function persist(kind: string, data: unknown) {
  const response = await fetch("/api/admin/storefront", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, data }) });
  const body = await response.json(); if (!response.ok) throw new Error(body.error || "تعذر الحفظ");
}
function ProductPresentationForm({ product }: { product: PresentationProduct }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); const data = new FormData(event.currentTarget);
    try { await persist("product", { id: product.id, published: data.get("published") === "on", featured: data.get("featured") === "on", inspiredBy: data.get("inspiredBy"), scentFamily: data.get("scentFamily"), badge: data.get("badge"), description: data.get("description"), category: data.get("category"), images: urls(String(data.get("images"))) }); setMessage("تم حفظ ظهور المنتج في المتجر"); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  return <details className="group self-start overflow-hidden open:col-span-full rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="cursor-pointer list-none group-open:max-w-xs marker:hidden [&::-webkit-details-marker]:hidden"><AdminProductPreview product={product}/><div className="flex items-center justify-between gap-2 p-3 text-xs font-semibold text-[#191735]"><span>تعديل بيانات المتجر</span><span aria-hidden="true">⌄</span></div></summary><Link href={`/dashboard/products/${product.id}/edit`} className="m-3 block rounded-lg bg-[#f0edf7] px-3 py-2 text-center text-xs text-[#191735]">تعديل الأحجام والأسعار</Link><form onSubmit={save} className="space-y-5 border-t p-5"><fieldset disabled={busy} className="space-y-5"><div className="flex flex-wrap gap-5 text-sm"><label><input name="published" type="checkbox" defaultChecked={product.storefrontPublished} /> نشر في المتجر</label><label><input name="featured" type="checkbox" defaultChecked={product.storefrontFeatured} /> Best Seller</label></div><label className="block text-sm font-semibold">موجّه إلى<select className={field} name="category" defaultValue={isSample(product.storefrontCategory) ? `Samples:${{ men: "Men", women: "Women", unisex: "Unisex" }[productAudience(product.storefrontCategory)]}` : productAudience(product.storefrontCategory) === "men" ? "Men" : productAudience(product.storefrontCategory) === "women" ? "Women" : "Unisex"}><option value="Men">رجالي</option><option value="Women">حريمي</option><option value="Unisex">للجنسين (Unisex)</option><option value="Samples:Men">سامبل رجالي</option><option value="Samples:Women">سامبل حريمي</option><option value="Samples:Unisex">سامبل للجنسين</option></select></label><label className="block text-sm font-semibold">وصف المنتج للعملاء<textarea className={field} name="description" rows={4} maxLength={10000} defaultValue={product.storefrontDescription} placeholder="وصف الرائحة والمكونات العطرية وطابعها" /></label><label className="block text-sm font-semibold">مستوحى من (اختياري)<input className={field} name="inspiredBy" maxLength={160} defaultValue={product.storefrontInspiredBy} placeholder="Kayali · Vanilla 28" /></label><label className="block text-sm font-semibold">طابع العطر (اختياري)<input className={field} name="scentFamily" maxLength={80} defaultValue={product.storefrontScentFamily} placeholder="Warm Sweet" /></label><label className="block text-sm font-semibold">نص البادج (اختياري)<input className={field} name="badge" maxLength={24} defaultValue={product.storefrontBadge} placeholder="20% OFF" /></label><div className="block text-sm font-semibold">صور المنتج<ImageLinks name="images" initial={product.storefrontImages} /></div></fieldset><button disabled={busy} className="rounded-xl bg-[#191735] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "جارٍ الحفظ…" : "حفظ بيانات المتجر"}</button>{message && <p role="status" className="text-sm">{message}</p>}</form></details>;
}
export function StorefrontAdmin({ settings, products, owner }: { settings: ShopSettings; products: PresentationProduct[]; owner: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [failed, setFailed] = useState(false);
  const [heroMode, setHeroMode] = useState(settings.heroMode);
  const [tab, setTab] = useState(owner ? "appearance" : "products"); const [enabled, setEnabled] = useState(settings.enabled); const [toggling, setToggling] = useState(false);
  async function toggle() {
    setToggling(true); setMessage(""); setFailed(false);
    try { await persist("availability", { enabled: !enabled }); setEnabled(!enabled); setMessage(!enabled ? "المتجر متاح لاستقبال الطلبات الآن" : "تم إيقاف استقبال الطلبات"); router.refresh(); }
    catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setToggling(false); }
  }
  async function saveSettings(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setMessage(""); setFailed(false);
    try { await persist("settings", { ...settings, enabled, bloggerReviewsEnabled: data.get("bloggerReviewsEnabled") === "on", bloggerReviewsTitle: data.get("bloggerReviewsTitle"), bloggerReviewVideos: data.getAll("bloggerReviewVideo").map(String).map(value => value.trim()).filter(Boolean), customerReviewsEnabled: data.get("customerReviewsEnabled") === "on", customerReviewsTitle: data.get("customerReviewsTitle"), customerReviewImages: urls(String(data.get("customerReviewImages") || "")), announcement: data.get("announcement"), announcementBackground: data.get("announcementBackground"), announcementTextColor: data.get("announcementTextColor"), announcements: String(data.get("announcements") || "").split("\n").map(value => value.trim()).filter(Boolean), announcementInterval: Number(data.get("announcementInterval")), heroTitle: data.get("heroTitle"), heroImages: urls(String(data.get("heroImages"))), samplesImage: String(data.get("samplesImage") || ""), heroMode, heroInterval: Number(data.get("heroInterval")), heroVideo: data.get("heroVideo"), menCollectionLabel: data.get("menCollectionLabel"), womenCollectionLabel: data.get("womenCollectionLabel"), featuredEyebrow: data.get("featuredEyebrow"), featuredTitle: data.get("featuredTitle"), offersTitle: data.get("offersTitle"), allProductsTitle: data.get("allProductsTitle"), storyEyebrow: data.get("storyEyebrow"), storyTitle: data.get("storyTitle"), storyDescription: data.get("storyDescription"), storyButtonLabel: data.get("storyButtonLabel"), whatsapp: data.get("whatsapp"), contactEmail: data.get("contactEmail"), shippingRates: Object.fromEntries(governorates.flatMap(name => { const value = String(data.get(`shipping-${name}`) ?? "").trim(); return value === "" ? [] : [[name, Number(value)]]; })), shippingFee: Number(data.get("shippingFee")), freeShippingFrom: Number(data.get("freeShippingFrom")), shippingPolicy: data.get("shippingPolicy"), returnPolicy: data.get("returnPolicy") }); setMessage("تم حفظ إعدادات الموقع بنجاح"); router.refresh(); }
    catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  return <div className="space-y-6"><section className="rounded-3xl bg-[#191735] p-6 text-white sm:p-8"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-sm text-[#ffe8a1]">حالة متجر Auraic</p><h2 className="mt-2 text-2xl font-bold">{enabled ? "جاهز لاستقبال طلبات عملائك" : "استقبال الطلبات متوقف"}</h2><p className="mt-2 text-sm text-slate-300">{products.filter(p => p.storefrontPublished && p.ready).length} منتجات جاهزة للبيع · {products.length} منتجات في الكتالوج</p></div>{owner && <button type="button" role="switch" aria-checked={enabled} disabled={toggling || busy} onClick={toggle} className="rounded-xl bg-[#ffe8a1] px-5 py-3 font-semibold text-[#191735] disabled:opacity-50">{toggling ? "جارٍ الحفظ…" : enabled ? "إيقاف استقبال الطلبات" : "جعل المتجر متاحًا لاستقبال الطلبات"}</button>}</div><p className="mt-4 text-xs text-slate-300">حالة استقبال الطلبات تتحفظ فورًا. راجع السياسات والتواصل قبل بدء البيع.</p></section>
    {message && <p role={failed ? "alert" : "status"} className={`sticky top-3 z-10 rounded-xl p-4 text-sm ${failed ? "bg-red-50 text-red-800" : "bg-emerald-50 text-emerald-800"}`}>{message}</p>}
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="أقسام إدارة الموقع">{[...(owner ? [["appearance", "التصميم والبانرات"], ["reviews", "الريفيوهات والتقييمات"], ["shipping", "الشحن والسياسات"], ["contact", "التواصل"]] : []), ["products", "منتجات المتجر"]].map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`shrink-0 rounded-xl px-5 py-3 text-sm font-semibold ${tab === key ? "bg-[#191735] text-white" : "border bg-white text-slate-500"}`}>{label}</button>)}</nav>
    {owner && <form noValidate onSubmit={saveSettings} hidden={tab === "products"} className={card}><fieldset disabled={busy || toggling} className="space-y-5">
      <div hidden={tab !== "appearance"} className="space-y-5"><h2 className="text-xl font-bold">هوية الموقع والواجهة الرئيسية</h2><div className="flex flex-wrap gap-6"><label className="text-sm font-semibold">لون خلفية الشريط<input type="color" name="announcementBackground" defaultValue={settings.announcementBackground} className="mt-2 block h-12 w-24 cursor-pointer rounded-lg border" /></label><label className="text-sm font-semibold">لون كتابة الشريط<input type="color" name="announcementTextColor" defaultValue={settings.announcementTextColor} className="mt-2 block h-12 w-24 cursor-pointer rounded-lg border" /></label></div><label className="block text-sm font-semibold">نص الشريط العلوي<input className={field} name="announcement" defaultValue={settings.announcement} maxLength={160} /></label><label className="block text-sm font-semibold">رسائل الشريط العلوي (كل رسالة في سطر)<textarea className={field} name="announcements" defaultValue={settings.announcements.join("\n")} rows={4} maxLength={1610}/><span className="text-xs text-slate-500">حتى 10 رسائل، كل رسالة حتى 160 حرفًا. لو فارغة يظهر النص الأساسي.</span></label><label className="block text-sm font-semibold">سرعة حركة الشريط (2–60، الأعلى أبطأ)<input className={field} name="announcementInterval" type="number" min={2} max={60} required defaultValue={settings.announcementInterval}/></label><label className="block text-sm font-semibold">عنوان الهيرو الظاهر للعميل<textarea dir="ltr" className={field} name="heroTitle" defaultValue={settings.heroTitle} required rows={3} maxLength={120} /></label><label className="block text-sm font-semibold">نوع الهيرو<select className={field} value={heroMode} onChange={e => setHeroMode(e.target.value as "images" | "video")}><option value="images">صور سلايدر</option><option value="video">فيديو</option></select></label><label className="block text-sm font-semibold">مدة كل صورة (ثوانٍ، من 2 إلى 60)<input className={field} name="heroInterval" type="number" min={2} max={60} defaultValue={settings.heroInterval} /></label><VideoUpload initial={settings.heroVideo} /><p className="text-xs text-slate-500">روابط مشاركة Facebook وYouTube لا تشغّل فيديو الهيرو؛ استخدم رابط ملف فيديو مباشر. الفيديو يعمل تلقائيًا وصامتًا بدون زر إيقاف. أول صورة تستخدم كغلاف أثناء تحميله. وضع الصور لا يشغّل الفيديو.</p><div className="text-sm font-semibold">صورة قسم السامبلز<ImageLinks name="samplesImage" maxImages={1} initial={settings.samplesImage ? [settings.samplesImage] : []} /></div><div className="text-sm font-semibold">صور البانرات<ImageLinks name="heroImages" initial={settings.heroImages} /></div></div>
      <div hidden={tab !== "appearance"} className="space-y-5 rounded-xl bg-slate-50 p-5"><h3 className="font-bold">زرارا الأقسام داخل الهيرو</h3><p className="text-sm text-slate-500">تصنيف المنتج رجالي أو حريمي أو للجنسين يحدد ظهوره في الزرارين. الصور تأتي من خلفية الهيرو.</p>{[["men", "رجالي"], ["women", "حريمي"]].map(([key, label]) => <section key={key} className="space-y-3"><h4 className="font-semibold">عطور {label}</h4><label className="block text-sm">النص الظاهر على الزر<input dir="ltr" className={field} name={`${key}CollectionLabel`} required maxLength={40} defaultValue={key === "men" ? settings.menCollectionLabel : settings.womenCollectionLabel} /></label></section>)}<datalist id="collection-categories">{[...new Set(products.map(p => p.storefrontCategory))].map(category => <option key={category} value={category} />)}</datalist></div>
      <div hidden={tab !== "appearance"} className="space-y-5 rounded-xl bg-slate-50 p-5"><h3 className="font-bold">قسم المنتجات المختارة والتعريف بالعلامة</h3><p className="text-sm text-slate-500">هذه النصوص تظهر مباشرة في الصفحة الرئيسية. زر SHOW NOTES يعرض وصف كل عطر المسجل في منتجات المتجر.</p>{([
        ["featuredEyebrow", "النص الصغير فوق المنتجات", 80, 1], ["featuredTitle", "عنوان Best Sellers", 120, 2], ["offersTitle", "عنوان Offers", 120, 1], ["allProductsTitle", "عنوان All Products", 120, 1],
        ["storyEyebrow", "النص الصغير في جزء التعريف", 80, 1], ["storyTitle", "عنوان التعريف", 160, 2],
        ["storyDescription", "وصف التعريف", 600, 3], ["storyButtonLabel", "نص زر التعريف", 60, 1],
      ] as const).map(([name, label, maxLength, rows]) => <label key={name} className="block text-sm font-semibold">{label}<textarea dir="ltr" className={field} name={name} defaultValue={settings[name]} maxLength={maxLength} rows={rows} /></label>)}<div className="rounded-xl bg-[#19183B] p-4 text-[#FAEAB1] text-sm">هوية Auraic الحالية: كحلي #19183B · كريمي #FAEAB1 · بنفسجي #3F3A60</div></div>
      <div hidden={tab !== "reviews"} className="space-y-6"><ReviewSettings settings={settings}/></div>
      <div hidden={tab !== "contact"} className="space-y-5"><h2 className="text-xl font-bold">تواصل العملاء معك</h2><label className="block text-sm font-semibold">رقم واتساب<input className={field} name="whatsapp" dir="ltr" defaultValue={settings.whatsapp} placeholder="010xxxxxxxx أو +2010xxxxxxxx" /></label><label className="block text-sm font-semibold">بريد التواصل<input className={field} type="email" name="contactEmail" defaultValue={settings.contactEmail} /></label></div>
      <div hidden={tab !== "shipping"} className="space-y-5"><h2 className="text-xl font-bold">الشحن والسياسات</h2><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">رسوم الشحن الافتراضية (جنيه)<input className={field} type="number" name="shippingFee" min={0} max={10000} step="0.01" required defaultValue={settings.shippingFee} /></label><label className="text-sm font-semibold">شحن مجاني من (0 لإيقافه)<input className={field} type="number" name="freeShippingFrom" min={0} max={1000000} step="0.01" required defaultValue={settings.freeShippingFrom} /></label></div><section><h3 className="font-bold">الشحن حسب المحافظة</h3><p className="mt-2 text-sm text-slate-500">حدد ٦٠ أو ٩٠ أو أي سعر لكل محافظة. الحقل الفارغ يستخدم الرسوم الافتراضية.</p><div className="mt-4 grid gap-4 sm:grid-cols-3">{governorates.map(name => <label key={name} className="text-sm font-semibold">{name}<input className={field} type="number" min={0} max={10000} step="0.01" name={`shipping-${name}`} defaultValue={settings.shippingRates[name] ?? ""} placeholder={String(settings.shippingFee)} /></label>)}</div></section><label className="block text-sm font-semibold">سياسة الشحن<textarea className={field} name="shippingPolicy" defaultValue={settings.shippingPolicy} rows={5} maxLength={5000} /></label><label className="block text-sm font-semibold">سياسة الاستبدال والإرجاع<textarea className={field} name="returnPolicy" defaultValue={settings.returnPolicy} rows={5} maxLength={5000} /></label></div>
    </fieldset><footer className="sticky bottom-24 rounded-xl bg-white pt-3 sm:bottom-4"><button disabled={busy || toggling} className="w-full rounded-xl bg-[#191735] px-5 py-3 font-semibold text-white disabled:opacity-50">{busy ? "جارٍ الحفظ…" : "حفظ تعديلات الموقع"}</button></footer></form>}
    <section hidden={tab !== "products"} className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">منتجات المتجر</h2><p className="mt-2 text-sm text-slate-500">صور ووصف ونشر المنتج، وتعديل الأحجام والأسعار والوصفات.</p></div><Link href="/dashboard/products/new" className="rounded-xl bg-[#191735] px-5 py-3 text-sm font-semibold text-white">+ إضافة عطر</Link></div><div className="grid grid-cols-2 items-start gap-3 lg:grid-cols-3">{products.map(product => <ProductPresentationForm key={product.id} product={product} />)}</div>{!products.length && <p className={card}>ابدأ بإضافة أول عطر وأحجامه.</p>}</section>
  </div>;
}

function ReviewSettings({ settings }: { settings: ShopSettings }) {
  const [slots, setSlots] = useState(settings.bloggerReviewVideos.map((url, id) => ({ url, id })));
  const [nextId, setNextId] = useState(slots.length);
  return <><section className="space-y-4"><h2 className="text-xl font-bold">ريفيوهات البلوجرز</h2><label className="flex gap-2"><input type="checkbox" name="bloggerReviewsEnabled" defaultChecked={settings.bloggerReviewsEnabled}/> إظهار قسم فيديوهات البلوجرز</label><label className="block">عنوان القسم<input className={field} name="bloggerReviewsTitle" defaultValue={settings.bloggerReviewsTitle} maxLength={120}/></label><p className="text-sm text-slate-500">حتى 20 فيديو. ترتيب الإضافة هو ترتيب العرض؛ احفظ بعد الرفع أو الحذف.</p>{slots.map(slot => <div key={slot.id}><VideoUpload initial={slot.url} name="bloggerReviewVideo" label="فيديو ريفيو"/><button type="button" className="mt-2 text-sm text-red-700" onClick={() => setSlots(current => current.filter(item => item.id !== slot.id))}>حذف الريفيو</button></div>)}<button type="button" disabled={slots.length >= 20} className="rounded-xl border px-4 py-3 disabled:opacity-50" onClick={() => { setSlots(current => [...current, { url: "", id: nextId }]); setNextId(nextId + 1); }}>+ إضافة فيديو ريفيو</button></section><section className="space-y-4 border-t pt-6"><h2 className="text-xl font-bold">تقييمات العملاء</h2><label className="flex gap-2"><input type="checkbox" name="customerReviewsEnabled" defaultChecked={settings.customerReviewsEnabled}/> إظهار قسم تقييمات العملاء</label><label className="block">عنوان القسم<input className={field} name="customerReviewsTitle" defaultValue={settings.customerReviewsTitle} maxLength={120}/></label><ImageLinks name="customerReviewImages" maxImages={20} initial={settings.customerReviewImages}/></section></>;
}
