"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ImageLinks } from "./ImageLinks";
import type { ShopSettings } from "@/lib/storefront/config";

type PresentationProduct = { id: string; title: string; storefrontPublished: boolean; storefrontFeatured: boolean; storefrontDescription: string; storefrontCategory: string; storefrontImages: string[]; ready: boolean };
const field = "mt-2 block w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#ab8c51]";
const card = "space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7";
const urls = (text: string) => text.split(/\n/).map(value => value.trim()).filter(Boolean);
async function persist(kind: string, data: unknown) {
  const response = await fetch("/api/admin/storefront", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, data }) });
  const body = await response.json(); if (!response.ok) throw new Error(body.error || "تعذر الحفظ");
}
function ProductPresentationForm({ product }: { product: PresentationProduct }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); const data = new FormData(event.currentTarget);
    try { await persist("product", { id: product.id, published: data.get("published") === "on", featured: data.get("featured") === "on", description: data.get("description"), category: data.get("category"), images: urls(String(data.get("images"))) }); setMessage("تم حفظ ظهور المنتج في المتجر"); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  return <details className="rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer items-center justify-between gap-3 p-5"><div><h3 className="font-bold">{product.title}</h3><p className="mt-1 text-xs text-slate-500">{product.storefrontPublished ? "منشور" : "مخفي عن العملاء"} · {product.ready ? "حجم بوصفة وسعر متاح" : "أضف حجمًا بسعر ووصفة قبل ظهوره للعملاء"}</p></div><Link href={`/dashboard/products/${product.id}/edit`} className="rounded-lg bg-[#f0edf7] px-3 py-2 text-xs text-[#191735]">تعديل الأحجام والأسعار</Link></summary><form onSubmit={save} className="space-y-5 border-t p-5"><fieldset disabled={busy} className="space-y-5"><div className="flex flex-wrap gap-5 text-sm"><label><input name="published" type="checkbox" defaultChecked={product.storefrontPublished} /> نشر في المتجر</label><label><input name="featured" type="checkbox" defaultChecked={product.storefrontFeatured} /> منتج مميز</label></div><label className="block text-sm font-semibold">قسم المنتج<input className={field} name="category" required maxLength={80} defaultValue={product.storefrontCategory} placeholder="مثال: عطور شرقية" /></label><label className="block text-sm font-semibold">وصف المنتج للعملاء<textarea className={field} name="description" rows={4} maxLength={10000} defaultValue={product.storefrontDescription} placeholder="وصف الرائحة والمكونات العطرية وطابعها" /></label><div className="block text-sm font-semibold">صور المنتج<ImageLinks name="images" initial={product.storefrontImages} /></div></fieldset><button disabled={busy} className="rounded-xl bg-[#191735] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "جارٍ الحفظ…" : "حفظ بيانات المتجر"}</button>{message && <p role="status" className="text-sm">{message}</p>}</form></details>;
}
export function StorefrontAdmin({ settings, products, owner }: { settings: ShopSettings; products: PresentationProduct[]; owner: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [failed, setFailed] = useState(false);
  const [tab, setTab] = useState(owner ? "appearance" : "products"); const [enabled, setEnabled] = useState(settings.enabled); const [toggling, setToggling] = useState(false);
  async function toggle() {
    setToggling(true); setMessage(""); setFailed(false);
    try { await persist("availability", { enabled: !enabled }); setEnabled(!enabled); setMessage(!enabled ? "المتجر متاح لاستقبال الطلبات الآن" : "تم إيقاف استقبال الطلبات"); router.refresh(); }
    catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setToggling(false); }
  }
  async function saveSettings(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setMessage(""); setFailed(false);
    try { await persist("settings", { enabled, announcement: data.get("announcement"), heroTitle: data.get("heroTitle"), heroSubtitle: data.get("heroSubtitle"), heroImages: urls(String(data.get("heroImages"))), whatsapp: data.get("whatsapp"), contactEmail: data.get("contactEmail"), shippingFee: Number(data.get("shippingFee")), freeShippingFrom: Number(data.get("freeShippingFrom")), shippingPolicy: data.get("shippingPolicy"), returnPolicy: data.get("returnPolicy") }); setMessage("تم حفظ إعدادات الموقع بنجاح"); router.refresh(); }
    catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setBusy(false); }
  }
  return <div className="space-y-6"><section className="rounded-3xl bg-[#191735] p-6 text-white sm:p-8"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-sm text-[#ffe8a1]">حالة متجر Auraic</p><h2 className="mt-2 text-2xl font-bold">{enabled ? "جاهز لاستقبال طلبات عملائك" : "استقبال الطلبات متوقف"}</h2><p className="mt-2 text-sm text-slate-300">{products.filter(p => p.storefrontPublished && p.ready).length} منتجات جاهزة للبيع · {products.length} منتجات في الكتالوج</p></div>{owner && <button type="button" role="switch" aria-checked={enabled} disabled={toggling || busy} onClick={toggle} className="rounded-xl bg-[#ffe8a1] px-5 py-3 font-semibold text-[#191735] disabled:opacity-50">{toggling ? "جارٍ الحفظ…" : enabled ? "إيقاف استقبال الطلبات" : "جعل المتجر متاحًا لاستقبال الطلبات"}</button>}</div><p className="mt-4 text-xs text-slate-300">حالة استقبال الطلبات تتحفظ فورًا. راجع السياسات والتواصل قبل بدء البيع.</p></section>
    {message && <p role={failed ? "alert" : "status"} className={`sticky top-3 z-10 rounded-xl p-4 text-sm ${failed ? "bg-red-50 text-red-800" : "bg-emerald-50 text-emerald-800"}`}>{message}</p>}
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="أقسام إدارة الموقع">{[...(owner ? [["appearance", "التصميم والبانرات"], ["shipping", "الشحن والسياسات"], ["contact", "التواصل"]] : []), ["products", "منتجات المتجر"]].map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`shrink-0 rounded-xl px-5 py-3 text-sm font-semibold ${tab === key ? "bg-[#191735] text-white" : "border bg-white text-slate-500"}`}>{label}</button>)}</nav>
    {owner && <form noValidate onSubmit={saveSettings} hidden={tab === "products"} className={card}><fieldset disabled={busy || toggling} className="space-y-5">
      <div hidden={tab !== "appearance"} className="space-y-5"><h2 className="text-xl font-bold">هوية الموقع والواجهة الرئيسية</h2><label className="block text-sm font-semibold">نص الشريط العلوي<input className={field} name="announcement" defaultValue={settings.announcement} maxLength={160} /></label><label className="block text-sm font-semibold">عنوان البانر<input className={field} name="heroTitle" defaultValue={settings.heroTitle} required maxLength={120} /></label><label className="block text-sm font-semibold">وصف البانر<textarea className={field} name="heroSubtitle" defaultValue={settings.heroSubtitle} rows={3} maxLength={400} /></label><div className="text-sm font-semibold">صور البانرات<ImageLinks name="heroImages" initial={settings.heroImages} /></div></div>
      <div hidden={tab !== "contact"} className="space-y-5"><h2 className="text-xl font-bold">تواصل العملاء معك</h2><label className="block text-sm font-semibold">رقم واتساب<input className={field} name="whatsapp" dir="ltr" defaultValue={settings.whatsapp} placeholder="010xxxxxxxx أو +2010xxxxxxxx" /></label><label className="block text-sm font-semibold">بريد التواصل<input className={field} type="email" name="contactEmail" defaultValue={settings.contactEmail} /></label></div>
      <div hidden={tab !== "shipping"} className="space-y-5"><h2 className="text-xl font-bold">الشحن والسياسات</h2><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">رسوم الشحن (جنيه)<input className={field} type="number" name="shippingFee" min={0} max={10000} step="0.01" required defaultValue={settings.shippingFee} /></label><label className="text-sm font-semibold">شحن مجاني من (0 لإيقافه)<input className={field} type="number" name="freeShippingFrom" min={0} max={1000000} step="0.01" required defaultValue={settings.freeShippingFrom} /></label></div><label className="block text-sm font-semibold">سياسة الشحن<textarea className={field} name="shippingPolicy" defaultValue={settings.shippingPolicy} rows={5} maxLength={5000} /></label><label className="block text-sm font-semibold">سياسة الاستبدال والإرجاع<textarea className={field} name="returnPolicy" defaultValue={settings.returnPolicy} rows={5} maxLength={5000} /></label></div>
    </fieldset><footer className="sticky bottom-24 rounded-xl bg-white pt-3 sm:bottom-4"><button disabled={busy || toggling} className="w-full rounded-xl bg-[#191735] px-5 py-3 font-semibold text-white disabled:opacity-50">{busy ? "جارٍ الحفظ…" : "حفظ تعديلات الموقع"}</button></footer></form>}
    <section hidden={tab !== "products"} className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">منتجات المتجر</h2><p className="mt-2 text-sm text-slate-500">صور ووصف ونشر المنتج، وتعديل الأحجام والأسعار والوصفات.</p></div><Link href="/dashboard/products/new" className="rounded-xl bg-[#191735] px-5 py-3 text-sm font-semibold text-white">+ إضافة عطر</Link></div>{products.map(product => <ProductPresentationForm key={product.id} product={product} />)}{!products.length && <p className={card}>ابدأ بإضافة أول عطر وأحجامه.</p>}</section>
  </div>;
}
